baseurl = "https://jerryyyyy708.github.io/Music_Site/"
metaDataFormat = "yaml"
title = "Jerrr Music Site"
theme = "blist"

DefaultContentLanguage = "zh-tw"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.zh-tw]
    contentDir = "content/zh-tw" #English
    weight = 1
    languageName = "中文"
    [languages.zh-tw.params]
      introTitle = "Jerrr, 一個愛編曲的研究生"
      introSubtitle = "這種文青風格超不適合我，而且我不知道要怎麼調字體。"
      introPhoto = "/new_jer.jpg"
      logo = "/blist-logo.png"
    [[languages.zh-tw.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.zh-tw.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 2

    [[languages.zh-tw.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

    [[languages.zh-tw.menu.main]]
        name = "Top Post"
        url = "/zh-tw/blog/emoji-support/"
        weight = 4


[params]
  # Enable the darkmode toggle in header
  darkModeToggle = false
  
  # Enable search in header
  enableSearch = false

  # Option to customize the search parameters of a page
  # Below are the supported options; Note that including entire content
  # may slowdown the loading of search results
  # Title of page is included by default
  searchKeys = [
    "tags",
    "date",
    "categories",
    "summary",
    "content",
    "link",
    "author"
  ]

  # Custom copyright - optional
  copyright = "Copyright © 2023 - Jerrr · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = true

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = true

  # Add support for Table of contents
  # Can be added to a page level also in markdown frontmatter
  toc = true

  # Hides the thumbnail in post view
  # Thumbnails in home and blog pages will still be shown
  # This setting can also be in page's markdown file
  hidePageThumbnail = false

# Comments system

[params.homepage.social]
  # Global params common for both languages
  title = "Follow me"
  description = "程式相關的點左邊三個，音樂相關的點右邊兩個。"

  [[params.homepage.social.icons]]
    website = "linkedin"
    url = "https://linkedin.com/in/"
  [[params.homepage.social.icons]]
    website = "github"
    url = "https://github.com/"
  [[params.homepage.social.icons]]
    website = "medium"
    url = "https://medium.com/"
  [[params.homepage.social.icons]]
    website = "youtube"
    url = "https://youtube.com"
  [[params.homepage.social.icons]]
    website = "instagram"
    url = "https://instagram.com"
 
[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
